### ISSUE TITLE
Cortana Disablement

### ISSUE THREAD

**Issue by Myke500** [private-locker/RegTweaksCMD#1]
![image](https://user-images.githubusercontent.com/17334141/49347080-99eb8b00-f64f-11e8-8f08-6e75f4777f37.png)

Disable Cortana Option: Y

Even with this option enabled, Cortana is still existing and operational.

A different key may still be active.

**Comment by PrivateLocker** [comment]
Going to look into seeing if there's a alternative key somewhere.

This function still disables Cortana for 75% of Users.
